version: '3.9'
services:
  wcb3:
    container_name: wcb3_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    entrypoint: ['python', 'bot.py']
    depends_on:
      - wcb3_postgres
        

  wcb3_postgres:
    container_name: wcb3_postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wcb3
      POSTGRES_PASSWORD: wcb3

    expose:
      - "5432"

    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
 
    ports:
      - 5432:5432

  adminer:
    container_name: wcb3_adminer_container
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - wcb3_postgres


volumes:
  postgres_data:

networks:
  esnet:

